export enum AuditLogAction {
  SCHEDULER_PAUSED = 'SCHEDULER_PAUSED',
  WORKER_DEAD_DETECTED = 'WORKER_DEAD_DETECTED',
  LEADER_ELECTED = 'LEADER_ELECTED',
  JOB_CREATED = 'JOB_CREATED',
  JOB_UPDATED = 'JOB_UPDATED',
  JOB_DELETED = 'JOB_DELETED',
  SYSTEM_SHUTDOWN = 'SYSTEM_SHUTDOWN',
  EMAIL_CONNECTION_FAILED = 'EMAIL_CONNECTION_FAILED',
}
